### ISSUE TITLE
error Can't add "sdk-v2": invalid package version undefined.

### ISSUE THREAD

**Issue by ltfschoen** [zeitgeistpm/sdk-next#11]
i wanted to test this repo.
so i created a repo and tried to add it as a dependency:
```
yarn init
yarn add zeitgeistpm/sdk-next#main
```
but it gave error `error Can't add "sdk-v2": invalid package version undefined.`, likely because there isn't a `"version":` number in the package.json file of this repo. i'm guessing it should be a prerelease version like alpha or beta https://github.com/npm/node-semver#functions

**Comment by ltfschoen** [comment]
actually perhaps it doesn't need a version number, since users would be installing specific packages like https://github.com/zeitgeistpm/sdk-next/blob/main/packages/sdk

but why is the version number in the latest 'main' branch here https://github.com/zeitgeistpm/sdk-next/blob/main/packages/sdk/package.json#L3 shown as `2.21.3`, but when i install the latest version with `yarn add @zeitgeistpm/sdk` it installs version `2.21.5`?
where is the source code for version `2.21.5`?

**Comment by yornaath** [comment]
The correct package name for the sdk-v2 is `@zeitgeistpm/sdk` same as with v1. Package version should now be up to date in the repo, forgot to push the latest changes although it was published.
