### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/me/game/node_modules/lodash-es/lodash.js from /node_modules/@zeitgeistpm/sdk/dist/model/swaps/pool.js not supported.

### ISSUE THREAD

**Issue by ltfschoen** [zeitgeistpm/sdk-next#12]
i'm trying to use this repo is because recently when i tried using the latest version of the Zeitgeist SDK published on npm by adding it with `yarn add @zeitgeistpm/sdk` so i had version "@zeitgeistpm/sdk": "^2.21.5" in the package.json file and node_modules, and then ran `node` and tried importing it with `require("@zeitgeistpm/sdk")` it output the following. i got the same error on Ubuntu and macOS, and using Node.js 16.8.1, 19.6.0, and 19.7.0

```
/Users/me/game/node_modules/@zeitgeistpm/sdk/dist/model/swaps/pool.js:9
var lodashEs = require('lodash-es');
               ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/me/game/node_modules/lodash-es/lodash.js from /Users/me/game/node_modules/@zeitgeistpm/sdk/dist/model/swaps/pool.js not supported.
Instead change the require of lodash.js in /Users/me/game/node_modules/@zeitgeistpm/sdk/dist/model/swaps/pool.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/me/game/node_modules/@zeitgeistpm/sdk/dist/model/swaps/pool.js:9:16)
    at Object.<anonymous> (/Users/me/game/node_modules/@zeitgeistpm/sdk/dist/model/markets/functions/create/index.js:7:12)
    at Object.<anonymous> (/Users/me/game/node_modules/@zeitgeistpm/sdk/dist/model/markets/index.js:5:15)
    at Object.<anonymous> (/Users/me/game/node_modules/@zeitgeistpm/sdk/dist/model/index.js:3:13)
    at Object.<anonymous> (/Users/me/game/node_modules/@zeitgeistpm/sdk/dist/types.js:5:15)
    at Object.<anonymous> (/Users/me/game/node_modules/@zeitgeistpm/sdk/dist/index.js:3:13)
    at Object.<anonymous> (/Users/me/game/scripts/createMarketOnZeitgeist.js:5:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v19.6.0
```

i old comments here https://github.com/sveltejs/kit/issues/1549#issuecomment-849736405 that suggested using lodash-es 4.17.15 instead of 4.17.21

i tried cloning this sdk-next repo, and switching to to node.js 16.8.1 with `nvm use 16.8.1`,
then i changed sdk-next dependency lodash-es in package.json to 4.17.15 before building dist/ with `yarn && yarn build` in the sdk-next project root

then i created a project with `yarn init`
added old dependency `yarn add lodash-es@4.17.15` to see if 4.17.15 worked instead of 4.17.21
then i copied across the latest sdk with:
```
cp -r packages/sdk/ /Users/me/myproject/node_modules/@zeitgeistpm/sdk
```
then in myproject i tried running
```
node
```
then in the Node.js REPL i tried to import that dependency with `require("@zeitgeistpm/sdk")` but got a different error:
```
Welcome to Node.js v16.18.1.
Type ".help" for more information.
> require("@zeitgeistpm/sdk")
/Users/me/myproject/node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^

Uncaught SyntaxError: Unexpected token 'export'
```

possibly related https://stackoverflow.com/questions/65981466/node-js-syntaxerror-unexpected-token-export

i tried switching to Node.js v15.14.0, since i noticed lodash hasn't been updated for like 2 years https://www.npmjs.com/package/lodash-es, and maybe an older version of Node.js might work https://nodejs.org/de/download/releases/

that older version actually provided a more helpful error than the new version:

```
Welcome to Node.js v15.14.0.
Type ".help" for more information.
> require("@zeitgeistpm/sdk")
Uncaught:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/me/myproject/node_modules/@zeitgeistpm/sdk/node_modules/lodash-es/lodash.js
require() of ES modules is not supported.
require() of /Users/me/myproject/node_modules/@zeitgeistpm/sdk/node_modules/lodash-es/lodash.js from /Users/me/myproject/node_modules/@zeitgeistpm/sdk/dist/model/swaps/pool.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename lodash.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/me/myproject/node_modules/@zeitgeistpm/sdk/node_modules/lodash-es/package.json.
```

**Comment by yornaath** [comment]
Unfortunately there is no quick fix for this as some of our libraries like the ipfs HTTP client is ESM only, so currently the SDK has to be imported as a ESM module using the `import` and not require.

**Comment by ltfschoen** [comment]
thanks. i tried it again. i just installed it 2.21.5 with `yarn add @zeitgeistpm/sdk`, and i found that i could get it to work when i ran a javascript file with the following:
```
(async () => {
    let { batterystation, create } = await import("@zeitgeistpm/sdk");
    const sdk = await create(batterystation());
    console.log('sdk', sdk);
})().catch(console.error).finally(() => process.exit());
```
i couldn't just do the following:
```
const { batterystation, create } = import("@zeitgeistpm/sdk");
async function createMarketOnZeitgeist () {
    const batterystationInstance = await batterystation();
    const sdk = await create(batterystationInstance);
    console.log('sdk', sdk);
}
createMarketOnZeitgeist().catch(console.error).finally(() => process.exit());
```
because `batterystation` and `create` themselves need to be loaded asynchronously from the library using `await` with `await import("@zeitgeistpm/sdk")`
but to use `await` it has to be in an async function or top level body of a module.

**Comment by yornaath** [comment]
@ltfschoen Have you tried doing this:

```ts
import { batterystation, create } from "@zeitgeistpm/sdk"

async function createMarketOnZeitgeist () {
    const sdk = await create(batterystation());
    console.log('sdk', sdk);
}

createMarketOnZeitgeist().catch(console.error).finally(() => process.exit());
```

And adding `"type": "module"` to your package json? _Allhough this might introduce other problems._

**Comment by ltfschoen** [comment]
i just tried the following and it works without having to add `"type": "module" in the package.json file

* example with server-side rendering https://nextjs.org/learn/excel/typescript/setup. running the `npm run dev` step populates tsconfig.json, installs typescript packages, and generates next-env.d.ts to enable typescript, then you can view the site at http://localhost:3000/ if you want but not relevant here...

```bash
npx create-next-app@latest nextjs-starter --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/basics-final"
cd nextjs-starter
npm install --save @zeitgeistpm/sdk
touch tsconfig.json
npm run dev
```

* create ./lib/getTestnetBatteryStation.js, and paste the following:

```js
import { batterystation, create } from "@zeitgeistpm/sdk"

export async function getTestnetBatteryStation() {
    const sdk = await create(batterystation());
    console.log('sdk: ', sdk, null, 2);
    return {
        sdk
    };
}
```

* edit ./pages/index.js

```
import { getTestnetBatteryStation } from '../lib/getTestnetBatteryStation'

export async function getStaticProps() {
  const sdk = getTestnetBatteryStation()
  console.log('sdk: ', sdk);
  return {
    props: {
      sdk
    }
  }
}
```

* view the terminal logs after saving your changes that should now the `sdk` Object

**Comment by ltfschoen** [comment]
so i converted FlappyTips 2 server code to ES6 syntax, but unfortunately i still get the error if i try to use that `import ... from ...` ES6 syntax here (i've commented it out because it gave that `lodash-es` error `Error [ERR_REQUIRE_ESM]: require() of ES Module`  https://github.com/ltfschoen/flappytips/pull/90/files#diff-f1f58bdd3af4dec2a82e6886ed7933deb7f863f3fc64c145c032392205812b63R85
it appears to compile using the CommonJS `require` and `await import` syntax here https://github.com/ltfschoen/flappytips/pull/90/files#diff-f1f58bdd3af4dec2a82e6886ed7933deb7f863f3fc64c145c032392205812b63R7, but i'm not sure how to export the `sdk` variable that's being obtained asynchronously in the IIFE, because it's value here https://github.com/ltfschoen/flappytips/pull/90/files#diff-e55e37faa04313cdad46c863c6ccad5697b7df184b50292f279512f736cdd9d8R46 is always undefined.

**Comment by ltfschoen** [comment]
> so i converted FlappyTips 2 server code to ES6 syntax so it uses Babel with outputs into dist-server/, but unfortunately i still get the error if i try to use that `import ... from ...` ES6 syntax here (i've commented it out because it gave that `lodash-es` error `Error [ERR_REQUIRE_ESM]: require() of ES Module` https://github.com/ltfschoen/flappytips/pull/90/files#diff-f1f58bdd3af4dec2a82e6886ed7933deb7f863f3fc64c145c032392205812b63R85 it appears to compile using the CommonJS `require` and `await import` syntax here https://github.com/ltfschoen/flappytips/pull/90/files#diff-f1f58bdd3af4dec2a82e6886ed7933deb7f863f3fc64c145c032392205812b63R7, but i'm not sure how to export the `sdk` variable that's being obtained asynchronously in the IIFE, because it's value here https://github.com/ltfschoen/flappytips/pull/90/files#diff-e55e37faa04313cdad46c863c6ccad5697b7df184b50292f279512f736cdd9d8R46 is always undefined.

actually, the only reason it was compiling is because i copied across the IIFEE code **incorrectly**, i had `(async () => { ... });` instead of `(async () => { ... })();`, so it wasn't even running that code.
as soon as i made that correction here https://github.com/ltfschoen/flappytips/pull/90/files#diff-f1f58bdd3af4dec2a82e6886ed7933deb7f863f3fc64c145c032392205812b63R7, when i build it with 
```
nvm use 19.7.0 && npm i -g yarn && npm install -g nodemon concurrently && . ./scripts/env_dev.sh && DEBUG=* yarn run dev
```
it outputs that `lodash-es` error `Error [ERR_REQUIRE_ESM]: require() of ES Module`
